name: 001-webapp-insights

trigger:
  - main

pool:
  vmImage: windows-2019

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $installPath = "$env:USERPROFILE\.bicep"
      $installDir = New-Item -ItemType Directory -Path $installPath -Force
      $installDir.Attributes += 'Hidden'
      (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$installPath\bicep.exe")
      $currentPath = (Get-Item -path "HKCU:\Environment" ).GetValue('Path', '', 'DoNotExpandEnvironmentNames')
      if (-not $currentPath.Contains("%USERPROFILE%\.bicep")) { setx PATH ($currentPath + ";%USERPROFILE%\.bicep") }
      if (-not $env:path.Contains($installPath)) { $env:path += ";$installPath" }
      bicep --help
    pwsh: true
  displayName: "Install bicep"
- task: PowerShell@2
  displayName: "Build bicep file"
  inputs:
    targetType: 'inline'
    script: |
      $env:USERPROFILE\.bicep\bicep.exe --help
    pwsh: true