name: 001-webapp-insights

variables:
  - name: installPath
    value: $(Agent.HomeDirectory)\tools\bicep
  - name: bicep
    value: $(installPath)\bicep.exe

trigger:
  - main
  
pool:
  vmImage: windows-2019

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $installDir = New-Item -ItemType Directory -Path $(installPath) -Force
      $installDir.Attributes += 'Hidden'
      (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$(installPath)\bicep.exe")
      if (-not $env:path.Contains('$(installPath)')) { $env:path += ";$(installPath)" }
    pwsh: true
  displayName: "Install bicep"
- task: PowerShell@2
  displayName: "Build bicep file"
  inputs:
    targetType: 'inline'
    script: |
      $(bicep) build $(System.DefaultWorkingDirectory)/001-webapp-insights/webapp-insights.bicep
    pwsh: true