name: 001-webapp-insights

variables:
  - name: installPath
    value: $(Agent.HomeDirectory)\tools\bicep
  - name: bicep
    value: $(installPath)\bicep.exe
  - name: filepath
    value: 001-webapp-insights/webapp-insights.bicep
trigger:
  - main
  
pool:
  vmImage: windows-2019

steps:
- task: PowerShell@2
  displayName: "Install bicep"
  inputs:
    targetType: 'inline'
    script: |
      $installDir = New-Item -ItemType Directory -Path $(installPath) -Force
      $installDir.Attributes += 'Hidden'
      (New-Object Net.WebClient).DownloadFile("https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe", "$(installPath)\bicep.exe")
    pwsh: true
- task: PowerShell@2
  displayName: "Build bicep file"
  inputs:
    targetType: 'inline'
    script: |
      $(bicep) build $(System.DefaultWorkingDirectory)/$(filepath)
    pwsh: true
- task: CopyFiles@2
  displayName: 'Copy files to ARM staging directory'
  inputs:
    SourceFolder: "$(System.DefaultWorkingDirectory)"
    Contents: "**/*.json"
    TargetFolder: "$(build.artifactstagingdirectory)/arm"
- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifacts'
  inputs:
    targetPath: "$(build.artifactstagingdirectory)/arm"
    artifact: "drop"
    publishLocation: "pipeline"
